services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - ../secrets/.env
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ../secrets/.env
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
  wordpress_files:

networks:
  inception:
